apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: demo-workload
spec:
  template:
    metadata:
      labels:
        nodepool: demo-workload
    spec:
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "eks.amazonaws.com/instance-family"
          operator: In
          values: ["c5"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In
          values: [ "large", "xlarge", "2xlarge"]
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      taints:
        - key: demo-workload
          value: "true"
          effect: NoSchedule
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
  limits:
    cpu: 1000
    memory: 1000Gi
