apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-worker-scaler
  namespace: workload
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  pollingInterval: 5
  cooldownPeriod: 300  # 5 min cooldown before scaling down
  minReplicaCount: 0   # Scale to zero when no jobs
  maxReplicaCount: 10
  triggers:
  - type: redis
    metadata:
      address: redis.workload.svc.cluster.local:6379
      listName: demo_queue
      listLength: '1'  # 1 pod per job
