name: Generate PlantUML diagrams

on:
  push:
    paths:
      - '**/images/*.puml'

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate PNGs
        uses: grassedge/generate-plantuml-action@v1
        with:
          path: '**/images'
          message: 'Auto-generate PlantUML diagrams'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
